-- Full Database Stabilization Script for GUIDIFY
-- Run this in the Supabase SQL Editor to fix missing tables and RLS issues.

-- 1. Create verified_courses Table (NCVET Compliance)
create table if not exists verified_courses (
  id bigint generated by default as identity primary key,
  course_name text not null,
  nsqf_level text, -- Storing as text to flexibility
  sector text,
  certification_body text,
  duration_hours int,
  min_eligibility text,
  job_roles text[],
  reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create ncvet_courses Table (Mirroring typical NCVET structure just in case)
create table if not exists ncvet_courses (
  course_id text primary key,
  title text not null,
  nsqf_level int,
  sector text,
  qp_code text,
  duration text,
  training_provider text,
  location text
);

-- 3. Fix Profiles RLS Policies (Prevent 401s)
-- First, drop ALL existing policies to clean up duplicates (checking both with and without periods)
drop policy if exists "Public profiles are viewable by everyone." on profiles;
drop policy if exists "Public profiles are viewable by everyone" on profiles;

drop policy if exists "Users can insert their own profile." on profiles;
drop policy if exists "Users can insert their own profile" on profiles;

drop policy if exists "Users can update own profile." on profiles;
drop policy if exists "Users can update own profile" on profiles;

drop policy if exists "Enable read access for all users" on profiles;
drop policy if exists "Enable insert for authenticated users only" on profiles;
drop policy if exists "Enable update for users based on email" on profiles;

drop policy if exists "Users can view own profile" on profiles;
drop policy if exists "Users can insert own profile" on profiles;
drop policy if exists "Users can update own profile" on profiles;

-- Enable RLS
alter table profiles enable row level security;
alter table verified_courses enable row level security;
alter table ncvet_courses enable row level security;

-- Create Clean Policies for Profiles
-- Allow users to see their own profile
create policy "Users can view own profile" on profiles
  for select using (auth.uid() = user_id);

-- Allow users to insert their own profile (Critical for Signup)
create policy "Users can insert own profile" on profiles
  for insert with check (auth.uid() = user_id);

-- Allow users to update their own profile
create policy "Users can update own profile" on profiles
  for update using (auth.uid() = user_id);

-- 4. Create Policies for Verified Courses (Public Read)
drop policy if exists "Public read access" on verified_courses;
create policy "Public read access" on verified_courses
  for select using (true);

drop policy if exists "Public read access" on ncvet_courses;
create policy "Public read access" on ncvet_courses
  for select using (true);

-- 5. Fix Login Streak / Gamification Tables if missing
create table if not exists user_quests (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    quest_id text not null,
    status text default 'active',
    progress int default 0,
    completed_at timestamp with time zone,
    created_at timestamp with time zone default now()
);
alter table user_quests enable row level security;

drop policy if exists "Users can view own quests" on user_quests;
create policy "Users can view own quests" on user_quests
  for select using (auth.uid() = user_id);
  
drop policy if exists "Users can update own quests" on user_quests;
create policy "Users can update own quests" on user_quests
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can modify own quests" on user_quests;
create policy "Users can modify own quests" on user_quests
  for update using (auth.uid() = user_id);
