-- GUIDIFY Phase 2 Migration: Daily Missions Table
-- Per schema.md §4 / remaining_tasks_report §2.1
-- Run after 002_roadmaps.sql

CREATE TABLE IF NOT EXISTS daily_missions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    learner_id UUID NOT NULL REFERENCES learners(id) ON DELETE CASCADE,
    roadmap_id UUID REFERENCES roadmaps(id) ON DELETE SET NULL,

    -- Mission content (generated by AI Gateway mission.generate)
    title TEXT NOT NULL,
    objective TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    steps JSONB NOT NULL DEFAULT '[]',          -- Array of step strings
    resources JSONB NOT NULL DEFAULT '[]',      -- Array of {title, url, type} objects

    -- Targeting
    target_skill TEXT NOT NULL DEFAULT '',
    roadmap_phase_number INT,                    -- Which phase this mission supports
    difficulty TEXT NOT NULL DEFAULT 'beginner' CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
    estimated_minutes INT NOT NULL DEFAULT 30 CHECK (estimated_minutes > 0 AND estimated_minutes <= 120),

    -- Status tracking
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'skipped', 'failed')),
    assigned_date DATE NOT NULL DEFAULT CURRENT_DATE,

    -- Completion data
    completed_at TIMESTAMPTZ,
    completion_notes TEXT,
    time_spent_minutes INT,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-update updated_at
CREATE TRIGGER update_daily_missions_updated_at
    BEFORE UPDATE ON daily_missions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_missions_learner_date ON daily_missions(learner_id, assigned_date DESC);
CREATE INDEX IF NOT EXISTS idx_missions_learner_status ON daily_missions(learner_id, status);
CREATE INDEX IF NOT EXISTS idx_missions_roadmap ON daily_missions(roadmap_id);

-- Unique constraint: one pending/in_progress mission per learner per day
CREATE UNIQUE INDEX IF NOT EXISTS idx_missions_learner_active_date
    ON daily_missions(learner_id, assigned_date)
    WHERE status IN ('pending', 'in_progress');

-- RLS: missions scoped by learner_id = auth.uid()
ALTER TABLE daily_missions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "missions_select_own" ON daily_missions
    FOR SELECT USING (auth.uid() = learner_id);

CREATE POLICY "missions_insert_own" ON daily_missions
    FOR INSERT WITH CHECK (auth.uid() = learner_id);

CREATE POLICY "missions_update_own" ON daily_missions
    FOR UPDATE USING (auth.uid() = learner_id);

-- Activity/Streak tracking view (used by dashboard)
-- Counts completed missions per day for streak calculation
CREATE OR REPLACE VIEW learner_activity_streaks AS
SELECT
    learner_id,
    assigned_date,
    COUNT(*) FILTER (WHERE status = 'completed') AS completed_count,
    COUNT(*) AS total_count
FROM daily_missions
GROUP BY learner_id, assigned_date;
